"use client";
import { useEffect, useMemo, useState } from "react";

type Form = { name:string; schoolType:string; school:string; grade:string; applicationDate:string; date:string; sr:string; level:string; className:string; director:string };
type ConsultationDraft = { id:string; form:Form; step:number; hasRtp:boolean; rtp:string; audio:string; summary:string; sttSummary:string; consult:string; comment:string; status:string; updatedAt:string };
type View = "new"|"history"|"files"|"settings";
type StoredFile = { id:string; name:string; category:"rtp"|"consultation"; contentType:string; size:number; createdAt:string; sample?:boolean };
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`};
const initialForm:Form={name:"",schoolType:"",school:"",grade:"",applicationDate:today(),date:today(),sr:"",level:"",className:"",director:""};
const sampleFiles:StoredFile[]=[
 {id:"sample-rtp-1",name:"김다은_RTP_테스트결과.pdf",category:"rtp",contentType:"application/pdf",size:1843200,createdAt:"2026-08-18T09:30:00+09:00",sample:true},
 {id:"sample-rtp-2",name:"박서준_RTP_Result_202608.pdf",category:"rtp",contentType:"application/pdf",size:2252800,createdAt:"2026-08-16T14:10:00+09:00",sample:true},
 {id:"sample-rtp-3",name:"최유나_STAR_Reading_Report.pdf",category:"rtp",contentType:"application/pdf",size:1320960,createdAt:"2026-08-12T11:20:00+09:00",sample:true},
 {id:"sample-rec-1",name:"김다은_학부모상담_0818.wav",category:"consultation",contentType:"audio/wav",size:28416400,createdAt:"2026-08-18T16:40:00+09:00",sample:true},
 {id:"sample-rec-2",name:"박서준_신규상담_0816.mp4",category:"consultation",contentType:"video/mp4",size:52738400,createdAt:"2026-08-16T15:30:00+09:00",sample:true},
];
const skills=[["어휘력",78,"학년 평균보다 풍부한 어휘를 이해하고 활용합니다."],["독해력",84,"글의 중심 생각과 세부 내용을 정확히 파악합니다."],["문법",64,"기본 문장 구조는 안정적이며 시제 보완이 필요합니다."],["추론력",72,"문맥을 바탕으로 의미를 유추하는 힘이 좋습니다."]] as const;

export default function Home(){
 const [view,setView]=useState<View>("history");
 const [pendingConsultation,setPendingConsultation]=useState<Form|null>(null);
 const [draftId,setDraftId]=useState("");
 const [drafts,setDrafts]=useState<ConsultationDraft[]>([]);
 const [consultationStatus,setConsultationStatus]=useState("상담 대기");
 const [step,setStep]=useState(1),[form,setForm]=useState(initialForm),[hasRtp,setHasRtp]=useState(true),[rtp,setRtp]=useState(""),[rtpUrl,setRtpUrl]=useState(""),[audio,setAudio]=useState(""),[loading,setLoading]=useState(false),[notice,setNotice]=useState("");
 const [summary,setSummary]=useState("다은 학생은 영어 원서를 읽고 핵심 내용을 파악하는 능력이 뛰어납니다. 특히 어휘와 독해 영역에서 또래 평균 이상의 강점을 보였습니다. 문법에서는 기본 문장 구조를 이해하고 있으나, 과거·현재 시제를 문맥에 맞게 구분하는 연습이 필요합니다.");
 const [consult,setConsult]=useState("학부모님은 영어 독서 습관 형성과 말하기 자신감 향상을 가장 중요하게 생각하고 계십니다. 학생은 영어 학습에 흥미가 높고 새로운 환경에도 긍정적입니다. 주 2회 정규 수업과 가정 독서 루틴을 병행하기로 협의했습니다.");
 const [sttSummary,setSttSummary]=useState("학부모는 독서 습관과 말하기 자신감 향상을 희망하며, 학생의 현재 흥미를 유지하면서 문법과 표현력을 단계적으로 보완하는 방향으로 상담했습니다.");
 const [comment,setComment]=useState("다은이는 이야기를 이해하고 자신의 생각으로 연결하는 힘이 좋은 학생입니다. 지금의 독서 흥미를 유지하면서 문법의 빈틈을 차근차근 채운다면 빠르게 성장할 수 있습니다. 다이브가 즐겁고 깊이 있는 영어 여정을 함께하겠습니다.");
 const initials=useMemo(()=>form.name.slice(-2),[form.name]);
 const update=(k:keyof Form,v:string)=>setForm(o=>({...o,[k]:v}));
 const studentInfoComplete=[form.name,form.schoolType,form.school,form.grade,form.applicationDate,form.date].every(value=>value.trim()!=="");
 const draftPayload={form,step,hasRtp,rtp,audio,summary,sttSummary,consult,comment,status:consultationStatus};
 const loadDrafts=async()=>{try{const res=await fetch("/api/consultations");if(res.ok){const data=await res.json() as {consultations:ConsultationDraft[]};setDrafts(data.consultations)}}catch{/* 로컬 API 준비 전에는 샘플 목록 유지 */}};
 useEffect(()=>{void loadDrafts()},[]);
 useEffect(()=>{if(consultationStatus==="결과 전송 완료"&&step===4)return;setConsultationStatus(step===1?"상담 대기":step<4?"상담 작성 중":"작성 완료")},[step,consultationStatus]);
 useEffect(()=>{if(!studentInfoComplete)return;const timer=setTimeout(async()=>{try{const res=await fetch("/api/consultations",{method:draftId?"PUT":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(draftId?{id:draftId,...draftPayload}:draftPayload)});if(res.ok){const data=await res.json() as {id:string};if(!draftId)setDraftId(data.id);setPendingConsultation({...form});await loadDrafts()}}catch{/* 입력 중 네트워크 오류는 다음 변경 때 재시도 */}},350);return()=>clearTimeout(timer)},[form,step,hasRtp,rtp,audio,summary,sttSummary,consult,comment,consultationStatus,studentInfoComplete,draftId]);
 const startConsultation=()=>{if(!studentInfoComplete)return;setNotice("상담 기록이 저장되었습니다. 언제든 현재 단계부터 이어갈 수 있습니다.");setStep(2)};
 const resumeDraft=(draft:ConsultationDraft)=>{setDraftId(draft.id);setForm(draft.form);setStep(draft.step);setConsultationStatus(draft.status==="결과 전송 완료"?draft.status:draft.step===1?"상담 대기":draft.step<4?"상담 작성 중":"작성 완료");setHasRtp(draft.hasRtp);setRtp(draft.rtp);setAudio(draft.audio);setSummary(draft.summary);setSttSummary(draft.sttSummary||"");setConsult(draft.consult);setComment(draft.comment);setView("new");setNotice("저장된 상담 단계를 불러왔습니다.")};
 const analyze=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setStep(3);setNotice("AI 분석이 완료되었습니다. 내용을 확인하고 수정해 주세요.")},1200)};
 const shareReport=async()=>{const url=`${window.location.origin}/?report=${encodeURIComponent(form.name||"dive-student")}`;try{if(navigator.share){await navigator.share({title:`${form.name||"학생"} 영어 성장 리포트`,text:"DIVE 상담 결과지를 확인해 주세요.",url})}else{await navigator.clipboard.writeText(url)}setConsultationStatus("결과 전송 완료");setNotice("결과지가 전송 완료 상태로 저장되었습니다.")}catch{/* 사용자가 공유 창을 닫은 경우 */}};
 const go=(next:View)=>{setView(next);setNotice("");if(next==="new"){setDraftId("");setConsultationStatus("상담 대기");setForm(initialForm);setStep(1)}};
 return <main>
  <header className="topbar"><div className="brand"><span className="brandmark"><img src="/dive-logo.png" alt="다이브 영어학원"/></span><span>DIVE</span><small>상담 리포트</small></div><div className="top-actions"><span className="status-dot"/> 시스템 정상 <button className="avatar">LS</button></div></header>
  <nav className="mobile-nav" aria-label="모바일 주 메뉴"><button className={view==="history"?"active":""} onClick={()=>go("history")}><span>▤</span>상담 기록</button><button className={view==="new"?"active":""} onClick={()=>go("new")}><span>＋</span>신규 상담</button><button className={view==="files"?"active":""} onClick={()=>go("files")}><span>⌘</span>첨부파일</button><button className={view==="settings"?"active":""} onClick={()=>go("settings")}><span>⚙</span>설정</button></nav>
  <section className="workspace"><aside className="sidebar"><div className="nav-label">상담 관리</div><button className={`nav ${view==="new"?"active":""}`} onClick={()=>go("new")}><span>＋</span>신규 상담 등록</button><button className={`nav ${view==="history"?"active":""}`} onClick={()=>go("history")}><span>▤</span>상담 기록</button><div className="nav-label lower">서비스</div><button className={`nav ${view==="files"?"active":""}`} onClick={()=>go("files")}><span>⌘</span>첨부파일 관리</button><button className={`nav ${view==="settings"?"active":""}`} onClick={()=>go("settings")}><span>⚙</span>설정</button><div className="sidebar-tip"><b>AI 요약 도우미</b><p>RTP 결과지와 상담 녹음을 올리면 핵심 내용을 자동으로 정리해 드려요.</p><span>자세히 보기 →</span></div></aside>
  <div className="content">
  {view==="new"&&<><div className="page-head"><div><p className="eyebrow">NEW CONSULTATION</p><h1>신규 상담 등록</h1><p>학생 정보와 상담 자료를 입력하면 다이브만의 맞춤 결과지가 완성됩니다.</p></div><button className="ghost" onClick={()=>{setDraftId("");setConsultationStatus("상담 대기");setForm(initialForm);setStep(1);setRtp("");setAudio("");setNotice("")}}>초기화</button></div>
  <ol className="stepper">{["신규 상담 정보 등록","레벨 테스트 결과 분석","학부모 상담 결과 입력","상담 결과 확인"].map((x,i)=><li key={x} className={step>=i+1?"on":""} onClick={()=>step>i&&setStep(i+1)}><span>{step>i+1?"✓":i+1}</span>{x}</li>)}</ol>{notice&&<div className="notice">✓ {notice}</div>}
  {step===1&&<section className="card"><Title icon="♙" title="학생 기본 정보" sub="결과지에 표시될 정보를 입력해 주세요." showRequired={false}/><div className="form-grid">
   <label>학생 이름<input value={form.name} placeholder="이연수" onChange={e=>update("name",e.target.value)}/></label>
   <label>학교 구분<select value={form.schoolType} onChange={e=>setForm(old=>({...old,schoolType:e.target.value,grade:""}))}><option value="">학교 구분을 선택해 주세요</option><option value="초등학교">초등학교</option><option value="중학교">중학교</option></select></label>
   <label>학교명<input value={form.school} placeholder={form.schoolType==="중학교"?"예: 연수중학교":"예: 연수초등학교"} onChange={e=>update("school",e.target.value)}/></label>
   <label>학년<select value={form.grade} disabled={!form.schoolType} onChange={e=>update("grade",e.target.value)}><option value="">{form.schoolType?"학년을 선택해 주세요":"학교 구분을 먼저 선택해 주세요"}</option>{(form.schoolType==="초등학교"?[1,2,3,4,5,6]:form.schoolType==="중학교"?[1,2,3]:[]).map(n=><option value={`${n}학년`} key={n}>{n}학년</option>)}</select></label>
   <label>상담 신청일<input type="date" value={form.applicationDate} onClick={e=>e.currentTarget.showPicker?.()} onChange={e=>{const value=e.target.value;setForm(old=>({...old,applicationDate:value,date:old.date<value?value:old.date}))}}/></label>
   <label>상담일<input type="date" min={form.applicationDate} value={form.date} onClick={e=>e.currentTarget.showPicker?.()} onChange={e=>update("date",e.target.value)}/></label>
  </div><Actions left={studentInfoComplete?"입력 내용은 결과지에 자동 반영됩니다.":"모든 필수 정보를 입력해 주세요."} next={startConsultation} text="다음 : 레테 분석 →" disabled={!studentInfoComplete}/></section>}
  {step===2&&<RtpAnalysis studentName={form.name} enabled={hasRtp} level={form.level} className={form.className} file={rtp} fileUrl={rtpUrl} summary={summary} loading={loading} setEnabled={(value)=>{setHasRtp(value);if(!value){setRtp("");setRtpUrl("")}}} setLevel={(value)=>update("level",value)} setClassName={(value)=>update("className",value)} setSummary={setSummary} onFile={(file)=>{setRtp(file.name);setRtpUrl(URL.createObjectURL(file))}} onExisting={(name)=>{setRtp(name);setRtpUrl("")}} onBack={()=>setStep(1)} onNext={hasRtp?analyze:()=>{setStep(3);setNotice("RTP 결과지 없이 상담 분석 단계로 이동했습니다.")}}/>}
  {step===3&&<ConsultationAnalysis file={audio} sttSummary={sttSummary} combined={consult} comment={comment} setSttSummary={setSttSummary} setCombined={setConsult} setComment={setComment} onFile={setAudio} onBack={()=>setStep(2)} onNext={()=>setStep(4)} onSave={()=>setNotice("수정 내용이 저장되었습니다.")}/>}
  {step===4&&<div className="share-bar"><div><span>↗</span><p><b>링크로 결과지 전달</b><small>학부모에게 전용 링크를 복사하거나 바로 공유할 수 있습니다.</small></p></div><button className="share-button" onClick={()=>void shareReport()}>링크 공유</button></div>}
  {step===4&&<section><div className="preview-actions"><button className="ghost" onClick={()=>setStep(3)}>← 내용 수정</button><div><button className="ghost" onClick={()=>window.print()}>인쇄 미리보기</button><button className="primary" onClick={()=>window.print()}>PDF 저장 / 인쇄</button></div></div><article className="report"><div className="report-top"><div className="report-brand">DIVE <span>ENGLISH</span></div><div>STUDENT CONSULTATION REPORT<br/><b>{form.date}</b></div></div><div className="hero-report"><div className="student-photo">{initials}</div><div><span className="report-kicker">DIVE LEARNING PROFILE</span><h2>{form.name} 학생의<br/><em>영어 성장 리포트</em></h2><p>{form.school} · {form.grade} | 상담자 {form.director}</p></div><div className="sr-card"><span>STAR READING</span><b>{form.sr}</b><small>GE / Grade Equivalent</small></div></div><div className="report-body"><ReportSection no="01" title="한눈에 보는 학습 프로필"><p className="lead">{summary}</p><div className="skills">{skills.map(([n,v,d])=><div className="skill" key={n}><div><b>{n}</b><span>{v}%</span></div><i><i style={{width:`${v}%`}}/></i><p>{d}</p></div>)}</div></ReportSection><ReportSection no="02" title="상담에서 발견한 성장 방향" cls="consult-box"><p>{consult}</p><div className="recommend"><span>RECOMMENDED CLASS</span><b>{form.className}</b><small>{form.level} · 주 2회 집중 과정</small></div></ReportSection><ReportSection no="03" title="다이브가 전하는 한마디"><blockquote>“{comment}”</blockquote><div className="signature">{form.director} <span>DIVE ENGLISH</span></div></ReportSection></div><footer className="report-footer"><b>깊이 읽고, 넓게 생각하는 영어</b><span>DIVE ENGLISH · 02-1234-5678 · dive-english.kr</span></footer></article></section>}</>}
  {view==="new"&&step===4&&<ReportContinuation form={form} comment={comment}/>}
  {view==="files"&&<AttachmentManager/>}
  {view==="history"&&<ConsultationHistory onNew={()=>go("new")} pending={pendingConsultation} drafts={drafts} onResume={resumeDraft} onChanged={loadDrafts}/>}
  {view==="settings"&&<SimplePage eyebrow="SETTINGS" title="설정" description="결과지 템플릿과 서비스 기본값을 관리합니다."/>}
  </div></section></main>
}
function RtpAnalysis({studentName,enabled,level,className,file,fileUrl,summary,loading,setEnabled,setLevel,setClassName,setSummary,onFile,onExisting,onBack,onNext}:{studentName:string;enabled:boolean;level:string;className:string;file:string;fileUrl:string;summary:string;loading:boolean;setEnabled:(x:boolean)=>void;setLevel:(x:string)=>void;setClassName:(x:string)=>void;setSummary:(x:string)=>void;onFile:(f:File)=>void;onExisting:(x:string)=>void;onBack:()=>void;onNext:()=>void}){
 const openPreview=()=>{if(fileUrl){window.open(fileUrl,"_blank","noopener,noreferrer");return}const win=window.open("","_blank","noopener,noreferrer");if(win){win.document.write(`<title>${file}</title><style>body{margin:0;background:#e9edf3;font-family:Arial;color:#25364d}.bar{height:58px;background:#233247;color:white;display:flex;align-items:center;padding:0 24px;font-size:13px}.page{width:720px;min-height:980px;margin:28px auto;background:white;padding:60px;box-sizing:border-box;box-shadow:0 8px 30px #26384d33}.tag{color:#2873dc;font-size:11px;font-weight:bold;letter-spacing:2px}h1{font-family:Georgia;font-size:32px}.score{margin:35px 0;background:#eef4ff;padding:25px;border-radius:10px;font-size:54px;color:#2769ce}.line{height:9px;background:#e6ebf2;margin:18px 0;border-radius:5px}.short{width:64%}</style><div class="bar">PDF 미리보기 · ${file}</div><main class="page"><span class="tag">STAR READING</span><h1>Student Progress Report</h1><div class="score">4.8</div><div class="line"></div><div class="line"></div><div class="line short"></div></main>`);win.document.close()}};
 return <section className={`analysis-page ${enabled?"":"rtp-disabled"}`}><div className="card analysis-card"><Title icon="PDF" title={`${studentName||"학생"} 학생의 RTP 결과 분석`} sub="RTP 테스트 결과지를 선택하고 AI 분석 내용을 확인해 주세요."/><label className="rtp-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/><span/><p><b>RTP 결과지 첨부</b><small>{enabled?"RTP 결과지를 분석해 상담 결과에 반영합니다.":"첨부하지 않고 상담 분석 단계로 바로 진행합니다."}</small></p></label><div className="source-switch"><div><span className="mini-label">새 파일 업로드</span><label className="source-upload"><input type="file" accept="application/pdf" onChange={e=>{const f=e.target.files?.[0];if(f)onFile(f)}}/><b>↥ 로컬에서 PDF 선택</b><small>{file||"선택된 파일이 없습니다."}</small></label></div><div className="or"><span>또는</span></div><label><span className="mini-label">기존 첨부파일 불러오기</span><select value={file&&!fileUrl?file:""} onChange={e=>onExisting(e.target.value)}><option value="">등록된 RTP 결과지 선택</option><option>김다은_RTP_테스트결과.pdf</option><option>박서준_RTP_Result_202608.pdf</option><option>최유나_STAR_Reading_Report.pdf</option></select></label></div></div>
 <div className="rtp-workspace">
 <div className="card summary-panel"><div className="edit-head"><div><span className="ai-tag">✦ AI 분석</span><h2>RTP 결과 요약</h2></div><span>직접 수정 가능</span></div><textarea value={summary} onChange={e=>setSummary(e.target.value)} placeholder="PDF를 분석한 결과가 이곳에 표시됩니다."/><div className="analysis-points"><b>분석 항목</b>{["읽기 수준과 SR 점수","어휘·독해·문법 강점","보완이 필요한 학습 영역"].map(x=><span key={x}>✓ {x}</span>)}{file&&<div className="pdf-preview-action"><div><span>PDF</span><p><b>{file}</b><small>선택한 RTP 결과지를 별도 창에서 확인할 수 있습니다.</small></p></div><button onClick={openPreview}>새 창에서 PDF 미리보기 ↗</button></div>}</div></div></div>
 <div className="card level-assignment"><div><span className="mini-label">RTP 레벨</span><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">RTP 레벨을 선택해 주세요</option><option value="A~C">A~C</option><option value="D~F">D~F</option><option value="G~K">G~K</option></select></div><div><span className="mini-label">반 레벨</span><select value={className} onChange={e=>setClassName(e.target.value)}><option value="">배정할 반을 선택해 주세요</option><option value="Ocean 1">Ocean 1</option><option value="Deep Blue 1">Deep Blue 1</option><option value="Deep Blue 2">Deep Blue 2</option><option value="Deep Blue 3">Deep Blue 3</option><option value="Deep Blue 4">Deep Blue 4</option></select></div></div>
 <div className="footer-actions"><button className="ghost" onClick={onBack}>← 학생 정보</button><button className="primary" onClick={onNext} disabled={loading||(enabled&&!file)}>{loading?"RTP 결과를 분석하고 있어요…":enabled?"분석 완료 · 상담 분석으로 →":"RTP 없이 상담 분석으로 →"}</button></div></section>
}

function ReportContinuation({form,comment}:{form:Form;comment:string}){
 const plan=[
  {week:"1–4주",title:"기초 진단과 학습 루틴",text:"수업 적응과 읽기 습관 형성에 집중하며 핵심 문장 구조와 필수 어휘를 점검합니다."},
  {week:"5–8주",title:"읽기 확장과 표현 연습",text:"레벨에 맞는 원서 읽기를 확장하고, 읽은 내용을 자신의 문장으로 말하고 쓰는 연습을 진행합니다."},
  {week:"9–12주",title:"성과 점검과 다음 목표",text:"독해 정확도와 표현력의 변화를 확인하고 다음 단계에 필요한 개인별 학습 목표를 설계합니다."},
 ];
 return <article className="report report-page-two"><div className="report-top"><div className="report-brand">DIVE <span>ENGLISH</span></div><div>PERSONAL LEARNING ROADMAP<br/><b>PAGE 02</b></div></div><div className="page-two-title"><span>PERSONALIZED ROADMAP</span><h2>{form.name||"학생"} 학생을 위한<br/><em>12주 영어 성장 로드맵</em></h2><p>진단 결과와 상담 내용을 바탕으로 다이브가 제안하는 학습 방향입니다.</p></div><div className="report-body page-two-body"><ReportSection no="04" title="단계별 학습 로드맵"><div className="roadmap">{plan.map((item,i)=><div key={item.week}><span>{String(i+1).padStart(2,"0")}</span><div><small>{item.week}</small><b>{item.title}</b><p>{item.text}</p></div></div>)}</div></ReportSection><ReportSection no="05" title="가정에서 함께해 주세요"><div className="home-guide"><div><b>20분 영어 독서</b><p>주 4회 이상, 수준에 맞는 원서를 소리 내어 읽고 재미있었던 문장을 표시해 주세요.</p></div><div><b>질문으로 생각 확장</b><p>정답 확인보다 “왜 그렇게 생각했어?”라는 질문으로 학생의 영어 사고를 격려해 주세요.</p></div><div><b>짧은 복습 습관</b><p>수업 당일 10분 동안 새 어휘와 핵심 문장을 다시 읽으며 기억을 단단하게 만들어 주세요.</p></div></div></ReportSection><ReportSection no="06" title="다이브가 전하는 한마디"><blockquote>“{comment}”</blockquote><div className="signature">{form.director||"다이브 원장"} <span>DIVE ENGLISH</span></div></ReportSection><div className="next-check"><span>NEXT CHECK-UP</span><div><b>첫 번째 성장 점검</b><strong>수업 시작 후 12주</strong><p>읽기 레벨, 수업 참여도, 가정 학습 기록을 함께 확인합니다.</p></div></div></div><footer className="report-footer"><b>깊이 읽고, 넓게 생각하는 영어</b><span>DIVE ENGLISH · 02-1234-5678 · dive-english.kr</span></footer></article>
}

function ConsultationAnalysis({file,sttSummary,combined,comment,setSttSummary,setCombined,setComment,onFile,onBack,onNext,onSave}:{file:string;sttSummary:string;combined:string;comment:string;setSttSummary:(x:string)=>void;setCombined:(x:string)=>void;setComment:(x:string)=>void;onFile:(x:string)=>void;onBack:()=>void;onNext:()=>void;onSave:()=>void}){
 const transcript=[
  {speaker:"원장",time:"00:18",text:"오늘 상담에서 가장 궁금하신 부분은 어떤 점인가요?"},
  {speaker:"학부모 1",time:"00:27",text:"아이가 책 읽기는 좋아하지만 영어로 말할 때 자신감이 부족한 편이에요."},
  {speaker:"원장",time:"00:42",text:"RTP 결과에서도 독해와 어휘는 강점으로 확인됐습니다. 말하기는 읽은 내용을 짧게 설명하는 연습부터 연결하면 좋겠습니다."},
  {speaker:"학부모 2",time:"01:05",text:"집에서는 어떤 방식으로 도와주면 좋을까요?"},
  {speaker:"원장",time:"01:14",text:"매일 20분 정도 함께 읽고, 정답을 묻기보다 기억에 남는 장면을 이야기하도록 격려해 주세요."},
 ];
 return <section className="consult-analysis"><div className="card"><Title icon="STT" title="상담 분석·편집" sub="상담 녹음을 선택하면 RTP 결과와 함께 종합 상담 내용을 구성합니다."/><div className="source-switch consult-source"><div><span className="mini-label">새 상담 파일 업로드</span><label className="source-upload"><input type="file" accept="audio/wav,video/mp4,audio/*" onChange={e=>onFile(e.target.files?.[0]?.name||"")}/><b>↥ WAV · MP4 선택</b><small>{file||"선택된 파일이 없습니다."}</small></label></div><div className="or"><span>또는</span></div><label><span className="mini-label">기존 상담 파일 불러오기</span><select value={file} onChange={e=>onFile(e.target.value)}><option value="">등록된 상담 녹음 선택</option><option>김다은_학부모상담_0818.wav</option><option>박서준_신규상담_0816.mp4</option></select></label></div></div>
 <div className="stt-grid"><div className="card compact transcript-card"><div className="edit-head"><div><span className="ai-tag">STT</span><h2>녹음 내용</h2></div><span>화자 자동 구분</span></div>{file?<div className="transcript-list">{transcript.map((line,index)=><div className={`transcript-line speaker-${line.speaker.replace(" ","")}`} key={`${line.time}-${index}`}><div><b>{line.speaker}</b><small>{line.time}</small></div><p>{line.text}</p></div>)}</div>:<div className="transcript-empty">상담 파일을 선택하면 원장·학부모별 대화 내용이 표시됩니다.</div>}</div><div className="card compact stt-summary-card"><div className="edit-head"><div><span className="ai-tag">✦ AI 요약</span><h2>녹음 내용 요약</h2></div><span>직접 수정 가능</span></div><textarea value={sttSummary} onChange={e=>setSttSummary(e.target.value)} placeholder="상담 녹음의 핵심 요청과 논의 내용을 요약합니다."/><button className="suggest-button" disabled={!file} onClick={()=>setSttSummary("학부모는 독서 습관과 말하기 자신감 향상을 희망하며, 학생의 독해·어휘 강점을 바탕으로 표현력과 문법을 단계적으로 보완하기로 상담했습니다.")}>✦ 녹음 내용 다시 요약</button></div></div>
 <div className="consult-grid"><div className="card compact combined-editor"><div className="edit-head"><div><span className="ai-tag">✦ 통합 AI 요약</span><h2>RTP 결과 + 상담 종합 요약</h2></div><span>학부모 제공 내용</span></div><textarea value={combined} onChange={e=>setCombined(e.target.value)} placeholder="RTP 결과와 상담 내용을 바탕으로 학생의 강점, 보완점, 학습 방향을 종합합니다."/><div className="source-chips"><span>✓ RTP 결과 반영</span><span className={file?"ready":""}>{file?"✓ 상담 녹음 반영":"○ 상담 파일 대기"}</span></div></div><div className="card compact director-editor"><div className="edit-head"><div><span className="director-chip">DIVE</span><h2>원장님의 한마디</h2></div><span>직접 입력·수정</span></div><textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="학생의 성장 가능성과 다이브의 학습 제안을 따뜻한 문장으로 작성해 주세요."/><button className="suggest-button" onClick={()=>setComment("학생의 강점을 바탕으로 자신감을 키우고, 필요한 영역은 단계적으로 보완할 수 있도록 다이브가 세심하게 함께하겠습니다.")}>✦ AI 문장 제안</button></div></div>
 <div className="footer-actions"><button className="ghost" onClick={onBack}>← RTP 분석</button><div><button className="ghost" onClick={onSave}>임시 저장</button><button className="primary" onClick={onNext}>결과지 미리보기 →</button></div></div></section>
}
function Title({icon,title,sub,showRequired=true}:{icon:string;title:string;sub:string;showRequired?:boolean}){return <div className="card-title"><span className="iconbox">{icon}</span><div><h2>{title}</h2><p>{sub}</p></div>{showRequired&&<span className="required">* 필수 입력</span>}</div>}
function Actions({left,next,text,disabled=false}:{left:string;next:()=>void;text:string;disabled?:boolean}){return <div className="footer-actions"><span>{left}</span><button className="primary" onClick={next} disabled={disabled}>{text}</button></div>}
function Upload({type,title,file,accept,set}:{type:string,title:string,file:string,accept:string,set:(x:string)=>void}){return <label className={`dropzone ${file?"filled":""}`}><input type="file" accept={accept} onChange={e=>set(e.target.files?.[0]?.name||"")}/><span className="upload-icon">{type}</span><h3>{file||title}</h3><p>{file?"파일이 준비되었습니다.":"파일을 끌어놓거나 클릭해 선택하세요."}</p><b>{file?"✓ 업로드 완료":"파일 선택"}</b></label>}
function Editor({tag,title,value,set}:{tag:string,title:string,value:string,set:(x:string)=>void}){return <div className="card compact"><div className="edit-head"><div><span className="ai-tag">{tag}</span><h2>{title}</h2></div><span>직접 수정 가능</span></div><textarea value={value} onChange={e=>set(e.target.value)}/></div>}
function ReportSection({no,title,cls="",children}:{no:string,title:string,cls?:string,children:React.ReactNode}){return <section className={cls}><div className="section-no">{no}</div><h3>{title}</h3>{children}</section>}
function SimplePage({eyebrow,title,description}:{eyebrow:string,title:string,description:string}){return <><div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></div><section className="card empty-state"><span>준비 중</span><h2>{title} 화면을 준비하고 있습니다.</h2><p>다음 기능 확장 시 실제 데이터와 연결됩니다.</p></section></>}

function ConsultationHistory({onNew,pending,drafts,onResume,onChanged}:{onNew:()=>void;pending:Form|null;drafts:ConsultationDraft[];onResume:(draft:ConsultationDraft)=>void;onChanged:()=>Promise<void>}){
 const [menu,setMenu]=useState("");
 const [hiddenSamples,setHiddenSamples]=useState<string[]>([]);
 const baseRows=[
  {name:"김다은",school:"연수초 · 4학년",date:"2026. 08. 18",sr:"4.8",className:"Deep Blue 2",status:"결과 전송 완료",tone:"sent"},
  {name:"박서준",school:"송도초 · 5학년",date:"2026. 08. 16",sr:"5.2",className:"Deep Blue 3",status:"작성 완료",tone:"done"},
  {name:"최유나",school:"해송초 · 3학년",date:"2026. 08. 12",sr:"3.6",className:"Ocean 1",status:"상담 작성 중",tone:"review"},
  {name:"정시우",school:"신정초 · 6학년",date:"2026. 08. 08",sr:"6.1",className:"Deep Blue 4",status:"상담 대기",tone:"waiting"},
  {name:"이하린",school:"먼우금초 · 4학년",date:"2026. 08. 05",sr:"4.3",className:"Deep Blue 1",status:"결과 전송 완료",tone:"sent"},
 ];
 const savedRows=drafts.map(draft=>{const status=draft.status==="결과 전송 완료"?draft.status:draft.step===1?"상담 대기":draft.step<4?"상담 작성 중":"작성 완료";return {name:draft.form.name,school:`${draft.form.school} · ${draft.form.grade}`,date:draft.form.date.replaceAll("-",". "),sr:draft.form.sr||"-",className:draft.form.className||"미정",status,tone:status==="결과 전송 완료"?"sent":status==="작성 완료"?"done":status==="상담 작성 중"?"review":"waiting",draft}});
 const fallbackRows=!savedRows.length&&pending?[{name:pending.name,school:`${pending.school} · ${pending.grade}`,date:pending.date.replaceAll("-",". "),sr:"-",className:"미정",status:"상담 대기",tone:"waiting"}]:[];
 const rows=[...savedRows,...fallbackRows,...baseRows.filter(row=>!hiddenSamples.includes(`${row.name}-${row.date}`))];
 const savedCount=savedRows.length||fallbackRows.length;
 const total=24+savedCount;
 const removeRow=async(row:typeof rows[number],key:string)=>{if(!confirm(`${row.name} 학생의 상담 기록을 삭제할까요?`))return;if("draft" in row){await fetch(`/api/consultations?id=${encodeURIComponent(row.draft.id)}`,{method:"DELETE"});await onChanged()}else{setHiddenSamples(old=>[...old,`${row.name}-${row.date}`])}setMenu("")};
 return <><div className="page-head"><div><p className="eyebrow">CONSULTATION HISTORY</p><h1>상담 기록</h1><p>등록한 상담과 결과지의 진행 상태를 한눈에 확인합니다.</p></div><button className="primary" onClick={onNew}>＋ 신규 상담 등록</button></div><div className="history-stats"><div><span>전체 상담</span><b>{total}</b><small>이번 달 +{8+savedCount}</small></div><div><span>결과지 완료</span><b>18</b><small>완료율 75%</small></div><div><span>검토 필요</span><b>4</b><small>확인이 필요해요</small></div><div><span>상담 대기</span><b>{2+savedCount}</b><small>진행 전 상담</small></div></div><section className="card history-card"><div className="history-tools"><div className="searchbox">⌕ <input placeholder="학생 이름 또는 학교 검색"/></div><div><button className="filter active">전체</button><button className="filter">진행 중</button><button className="filter">완료</button></div></div><div className="history-table"><div className="history-row header"><span>학생명</span><span>상담 진행 상태</span><span>상담일</span><span>RTP 점수</span><span>반배정</span><span>이어하기</span><span>더보기</span></div>{rows.map((row,index)=>{const key=`${row.name}-${row.date}-${index}`;return <div className={`history-row ${"draft" in row?"resumable":""}`} key={key}><span className="student-cell"><i>{row.name.slice(-2)}</i><b>{row.name}<small>{row.school}</small></b></span><span><em className={row.tone}>{row.status}</em></span><span>{row.date}</span><span><b>{row.sr}</b></span><span>{row.className}</span><span>{"draft" in row?<button className="continue-icon" onClick={()=>onResume(row.draft)} aria-label={`${row.name} 상담 이어서 작성`}>→</button>:<button className="continue-icon" disabled aria-label="완료된 샘플 상담">→</button>}</span><span className="more-cell"><button className="row-more" onClick={()=>setMenu(menu===key?"":key)} aria-label={`${row.name} 더보기`}>•••</button>{menu===key&&<div className="row-menu"><button onClick={()=>void removeRow(row,key)}>삭제하기</button></div>}</span></div>})}</div><div className="table-footer"><span>총 {total}개 중 1–{Math.min(rows.length,5+savedCount)}</span><div><button disabled>‹</button><button className="current">1</button><button>2</button><button>3</button><button>›</button></div></div></section></>
}

function AttachmentManager(){
 const [tab,setTab]=useState<"rtp"|"consultation">("rtp"),[files,setFiles]=useState<StoredFile[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{try{const res=await fetch("/api/files");if(res.ok){const data=await res.json() as {files:StoredFile[]};setFiles(data.files)}}catch{setMessage("파일 목록을 불러오지 못했습니다.")}};
 useEffect(()=>{void load()},[]);
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);setMessage("");const body=new FormData();body.append("file",file);body.append("category",tab);try{const res=await fetch("/api/files",{method:"POST",body});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error);setMessage("파일이 등록되었습니다.");await load()}catch(e){setMessage(e instanceof Error?e.message:"등록 중 오류가 발생했습니다.")}finally{setBusy(false)}};
 const remove=async(id:string)=>{if(!confirm("이 파일을 삭제할까요?"))return;await fetch(`/api/files?id=${encodeURIComponent(id)}`,{method:"DELETE"});setMessage("파일이 삭제되었습니다.");await load()};
 const filtered=[...sampleFiles,...files].filter(f=>f.category===tab);
 return <><div className="page-head attachment-head"><div><p className="eyebrow">FILE MANAGEMENT</p><h1>첨부파일 관리</h1><p>AI 분석에 사용하는 RTP 결과지와 상담 녹음 파일을 안전하게 관리합니다.</p></div><label className="primary upload-button">＋ 파일 등록<input type="file" accept={tab==="rtp"?"application/pdf":"audio/wav,video/mp4,audio/*,video/mp4"} onChange={e=>void upload(e.target.files?.[0])}/></label></div>
 <div className="file-tabs"><button className={tab==="rtp"?"active":""} onClick={()=>setTab("rtp")}><b>RTP 결과지</b><span>PDF</span></button><button className={tab==="consultation"?"active":""} onClick={()=>setTab("consultation")}><b>상담 녹음</b><span>WAV · MP4</span></button></div>
 {message&&<div className="notice">{message}</div>}<section className="card file-card"><div className="file-toolbar"><div><h2>{tab==="rtp"?"RTP 테스트 결과지":"상담 녹음 파일"}</h2><p>{tab==="rtp"?"학생의 RTP 테스트 결과 PDF를 관리합니다.":"학부모 상담 WAV·MP4 파일을 관리합니다."}</p></div><span>총 {filtered.length}개</span></div>
 {busy?<div className="file-empty">파일을 등록하고 있습니다…</div>:<div className="file-list">{filtered.map(file=><div className="file-row" key={file.id}><div className={`file-kind ${file.category}`}><b>{file.category==="rtp"?"PDF":"REC"}</b></div><div className="file-meta"><b>{file.name} {file.sample&&<small className="sample-label">샘플</small>}</b><span>{formatBytes(file.size)} · {new Date(file.createdAt).toLocaleDateString("ko-KR")}</span></div><span className="file-status">등록 완료</span>{file.sample?<><button className="icon-action" disabled title="샘플 파일">↓</button><button className="icon-action danger" disabled title="샘플 파일">×</button></>:<><a className="icon-action" href={`/api/files?id=${encodeURIComponent(file.id)}`} title="다운로드">↓</a><button className="icon-action danger" onClick={()=>void remove(file.id)} title="삭제">×</button></>}</div>)}</div>}</section></>
}
function formatBytes(size:number){return size<1024*1024?`${Math.max(1,Math.round(size/1024))} KB`:`${(size/1024/1024).toFixed(1)} MB`}
