"use client";
import { useEffect, useMemo, useState } from "react";

type Form = { name:string; school:string; grade:string; parent:string; date:string; sr:string; level:string; className:string; director:string };
type View = "new"|"history"|"files"|"settings";
type StoredFile = { id:string; name:string; category:"rtp"|"consultation"; contentType:string; size:number; createdAt:string };
const initialForm:Form={name:"김다은",school:"연수초등학교",grade:"4학년",parent:"김민지",date:"2026. 08. 20",sr:"4.8",level:"Intermediate",className:"Deep Blue 2",director:"이수진 원장"};
const skills=[["어휘력",78,"학년 평균보다 풍부한 어휘를 이해하고 활용합니다."],["독해력",84,"글의 중심 생각과 세부 내용을 정확히 파악합니다."],["문법",64,"기본 문장 구조는 안정적이며 시제 보완이 필요합니다."],["추론력",72,"문맥을 바탕으로 의미를 유추하는 힘이 좋습니다."]] as const;

export default function Home(){
 const [view,setView]=useState<View>("new");
 const [step,setStep]=useState(1),[form,setForm]=useState(initialForm),[rtp,setRtp]=useState(""),[audio,setAudio]=useState(""),[loading,setLoading]=useState(false),[notice,setNotice]=useState("");
 const [summary,setSummary]=useState("다은 학생은 영어 원서를 읽고 핵심 내용을 파악하는 능력이 뛰어납니다. 특히 어휘와 독해 영역에서 또래 평균 이상의 강점을 보였습니다. 문법에서는 기본 문장 구조를 이해하고 있으나, 과거·현재 시제를 문맥에 맞게 구분하는 연습이 필요합니다.");
 const [consult,setConsult]=useState("학부모님은 영어 독서 습관 형성과 말하기 자신감 향상을 가장 중요하게 생각하고 계십니다. 학생은 영어 학습에 흥미가 높고 새로운 환경에도 긍정적입니다. 주 2회 정규 수업과 가정 독서 루틴을 병행하기로 협의했습니다.");
 const [comment,setComment]=useState("다은이는 이야기를 이해하고 자신의 생각으로 연결하는 힘이 좋은 학생입니다. 지금의 독서 흥미를 유지하면서 문법의 빈틈을 차근차근 채운다면 빠르게 성장할 수 있습니다. 다이브가 즐겁고 깊이 있는 영어 여정을 함께하겠습니다.");
 const initials=useMemo(()=>form.name.slice(-2),[form.name]);
 const update=(k:keyof Form,v:string)=>setForm(o=>({...o,[k]:v}));
 const analyze=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setStep(3);setNotice("AI 분석이 완료되었습니다. 내용을 확인하고 수정해 주세요.")},1200)};
 const go=(next:View)=>{setView(next);setNotice("");if(next==="new")setStep(1)};
 return <main>
  <header className="topbar"><div className="brand"><span className="brandmark">D</span><span>DIVE</span><small>상담 리포트</small></div><div className="top-actions"><span className="status-dot"/> 시스템 정상 <button className="avatar">LS</button></div></header>
  <section className="workspace"><aside className="sidebar"><div className="nav-label">상담 관리</div><button className={`nav ${view==="new"?"active":""}`} onClick={()=>go("new")}><span>＋</span>신규 상담 등록</button><button className={`nav ${view==="history"?"active":""}`} onClick={()=>go("history")}><span>▤</span>상담 기록</button><div className="nav-label lower">서비스</div><button className={`nav ${view==="files"?"active":""}`} onClick={()=>go("files")}><span>⌘</span>첨부파일 관리</button><button className={`nav ${view==="settings"?"active":""}`} onClick={()=>go("settings")}><span>⚙</span>설정</button><div className="sidebar-tip"><b>AI 요약 도우미</b><p>RTP 결과지와 상담 녹음을 올리면 핵심 내용을 자동으로 정리해 드려요.</p><span>자세히 보기 →</span></div></aside>
  <div className="content">
  {view==="new"&&<><div className="page-head"><div><p className="eyebrow">NEW CONSULTATION</p><h1>신규 상담 등록</h1><p>학생 정보와 상담 자료를 입력하면 다이브만의 맞춤 결과지가 완성됩니다.</p></div><button className="ghost" onClick={()=>{setForm(initialForm);setStep(1)}}>초기화</button></div>
  <ol className="stepper">{["학생 정보","자료 업로드","AI 분석·편집","결과지 확인"].map((x,i)=><li key={x} className={step>=i+1?"on":""} onClick={()=>step>i&&setStep(i+1)}><span>{step>i+1?"✓":i+1}</span>{x}</li>)}</ol>{notice&&<div className="notice">✓ {notice}</div>}
  {step===1&&<section className="card"><Title icon="♙" title="학생 기본 정보" sub="결과지에 표시될 정보를 입력해 주세요."/><div className="form-grid">{([['name','학생 이름'],['school','학교'],['grade','학년'],['parent','보호자 이름'],['date','상담일'],['sr','SR 점수'],['level','RTP 레벨'],['className','추천 반']] as const).map(([k,l])=><label key={k}>{l}<input value={form[k]} onChange={e=>update(k,e.target.value)}/></label>)}</div><Actions left="입력 내용은 결과지에 자동 반영됩니다." next={()=>setStep(2)} text="다음: 자료 업로드 →"/></section>}
  {step===2&&<section className="card"><Title icon="↥" title="상담 자료 업로드" sub="AI가 분석할 RTP 결과지와 상담 녹음 파일을 선택해 주세요."/><div className="uploads"><Upload type="PDF" title="RTP 테스트 결과지" file={rtp} accept="application/pdf" set={setRtp}/><Upload type="STT" title="학부모 상담 녹음" file={audio} accept="audio/*,video/*" set={setAudio}/></div><div className="privacy">🔒 업로드된 자료는 결과지 생성에만 사용되며 안전하게 관리됩니다.</div><div className="footer-actions"><button className="ghost" onClick={()=>setStep(1)}>← 이전</button><button className="primary" onClick={analyze} disabled={loading}>{loading?"자료를 분석하고 있어요…":"AI 분석 시작 ✦"}</button></div></section>}
  {step===3&&<section className="editor-layout"><div className="editor-stack"><Editor tag="✦ AI 요약" title="RTP 테스트 분석" value={summary} set={setSummary}/><Editor tag="✦ STT 요약" title="학부모 상담 내용" value={consult} set={setConsult}/><Editor tag="DIVE" title="원장님 한마디" value={comment} set={setComment}/><div className="footer-actions"><button className="ghost" onClick={()=>setStep(2)}>← 이전</button><div><button className="ghost" onClick={()=>setNotice("수정 내용이 저장되었습니다.")}>임시 저장</button><button className="primary" onClick={()=>setStep(4)}>결과지 미리보기 →</button></div></div></div><aside className="quality"><h3>결과지 완성도</h3><div className="score-ring"><b>92</b><span>/100</span></div><p>모든 필수 항목이 채워졌어요.</p>{["학생 기본 정보","RTP 테스트 분석","상담 내용 요약","원장님 코멘트"].map(x=><div className="check" key={x}>✓ {x}</div>)}</aside></section>}
  {step===4&&<section><div className="preview-actions"><button className="ghost" onClick={()=>setStep(3)}>← 내용 수정</button><div><button className="ghost" onClick={()=>window.print()}>인쇄 미리보기</button><button className="primary" onClick={()=>window.print()}>PDF 저장 / 인쇄</button></div></div><article className="report"><div className="report-top"><div className="report-brand">DIVE <span>ENGLISH</span></div><div>STUDENT CONSULTATION REPORT<br/><b>{form.date}</b></div></div><div className="hero-report"><div className="student-photo">{initials}</div><div><span className="report-kicker">DIVE LEARNING PROFILE</span><h2>{form.name} 학생의<br/><em>영어 성장 리포트</em></h2><p>{form.school} · {form.grade} | 상담자 {form.director}</p></div><div className="sr-card"><span>STAR READING</span><b>{form.sr}</b><small>GE / Grade Equivalent</small></div></div><div className="report-body"><ReportSection no="01" title="한눈에 보는 학습 프로필"><p className="lead">{summary}</p><div className="skills">{skills.map(([n,v,d])=><div className="skill" key={n}><div><b>{n}</b><span>{v}%</span></div><i><i style={{width:`${v}%`}}/></i><p>{d}</p></div>)}</div></ReportSection><ReportSection no="02" title="상담에서 발견한 성장 방향" cls="consult-box"><p>{consult}</p><div className="recommend"><span>RECOMMENDED CLASS</span><b>{form.className}</b><small>{form.level} · 주 2회 집중 과정</small></div></ReportSection><ReportSection no="03" title="다이브가 전하는 한마디"><blockquote>“{comment}”</blockquote><div className="signature">{form.director} <span>DIVE ENGLISH</span></div></ReportSection></div><footer className="report-footer"><b>깊이 읽고, 넓게 생각하는 영어</b><span>DIVE ENGLISH · 02-1234-5678 · dive-english.kr</span></footer></article></section>}</>}
  {view==="files"&&<AttachmentManager/>}
  {view==="history"&&<SimplePage eyebrow="CONSULTATION HISTORY" title="상담 기록" description="등록한 상담과 결과지의 진행 상태를 확인합니다."/>}
  {view==="settings"&&<SimplePage eyebrow="SETTINGS" title="설정" description="결과지 템플릿과 서비스 기본값을 관리합니다."/>}
  </div></section></main>
}
function Title({icon,title,sub}:{icon:string,title:string,sub:string}){return <div className="card-title"><span className="iconbox">{icon}</span><div><h2>{title}</h2><p>{sub}</p></div><span className="required">* 필수 입력</span></div>}
function Actions({left,next,text}:{left:string,next:()=>void,text:string}){return <div className="footer-actions"><span>{left}</span><button className="primary" onClick={next}>{text}</button></div>}
function Upload({type,title,file,accept,set}:{type:string,title:string,file:string,accept:string,set:(x:string)=>void}){return <label className={`dropzone ${file?"filled":""}`}><input type="file" accept={accept} onChange={e=>set(e.target.files?.[0]?.name||"")}/><span className="upload-icon">{type}</span><h3>{file||title}</h3><p>{file?"파일이 준비되었습니다.":"파일을 끌어놓거나 클릭해 선택하세요."}</p><b>{file?"✓ 업로드 완료":"파일 선택"}</b></label>}
function Editor({tag,title,value,set}:{tag:string,title:string,value:string,set:(x:string)=>void}){return <div className="card compact"><div className="edit-head"><div><span className="ai-tag">{tag}</span><h2>{title}</h2></div><span>직접 수정 가능</span></div><textarea value={value} onChange={e=>set(e.target.value)}/></div>}
function ReportSection({no,title,cls="",children}:{no:string,title:string,cls?:string,children:React.ReactNode}){return <section className={cls}><div className="section-no">{no}</div><h3>{title}</h3>{children}</section>}
function SimplePage({eyebrow,title,description}:{eyebrow:string,title:string,description:string}){return <><div className="page-head"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{description}</p></div></div><section className="card empty-state"><span>준비 중</span><h2>{title} 화면을 준비하고 있습니다.</h2><p>다음 기능 확장 시 실제 데이터와 연결됩니다.</p></section></>}

function AttachmentManager(){
 const [tab,setTab]=useState<"rtp"|"consultation">("rtp"),[files,setFiles]=useState<StoredFile[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{try{const res=await fetch("/api/files");if(res.ok){const data=await res.json() as {files:StoredFile[]};setFiles(data.files)}}catch{setMessage("파일 목록을 불러오지 못했습니다.")}};
 useEffect(()=>{void load()},[]);
 const upload=async(file?:File)=>{if(!file)return;setBusy(true);setMessage("");const body=new FormData();body.append("file",file);body.append("category",tab);try{const res=await fetch("/api/files",{method:"POST",body});const data=await res.json() as {error?:string};if(!res.ok)throw new Error(data.error);setMessage("파일이 등록되었습니다.");await load()}catch(e){setMessage(e instanceof Error?e.message:"등록 중 오류가 발생했습니다.")}finally{setBusy(false)}};
 const remove=async(id:string)=>{if(!confirm("이 파일을 삭제할까요?"))return;await fetch(`/api/files?id=${encodeURIComponent(id)}`,{method:"DELETE"});setMessage("파일이 삭제되었습니다.");await load()};
 const filtered=files.filter(f=>f.category===tab);
 return <><div className="page-head attachment-head"><div><p className="eyebrow">FILE MANAGEMENT</p><h1>첨부파일 관리</h1><p>AI 분석에 사용하는 RTP 결과지와 상담 녹음 파일을 안전하게 관리합니다.</p></div><label className="primary upload-button">＋ 파일 등록<input type="file" accept={tab==="rtp"?"application/pdf":"audio/wav,video/mp4,audio/*,video/mp4"} onChange={e=>void upload(e.target.files?.[0])}/></label></div>
 <div className="file-tabs"><button className={tab==="rtp"?"active":""} onClick={()=>setTab("rtp")}><b>RTP 결과지</b><span>PDF</span></button><button className={tab==="consultation"?"active":""} onClick={()=>setTab("consultation")}><b>상담 녹음</b><span>WAV · MP4</span></button></div>
 {message&&<div className="notice">{message}</div>}<section className="card file-card"><div className="file-toolbar"><div><h2>{tab==="rtp"?"RTP 테스트 결과지":"상담 녹음 파일"}</h2><p>{tab==="rtp"?"학생의 RTP 테스트 결과 PDF를 관리합니다.":"학부모 상담 WAV·MP4 파일을 관리합니다."}</p></div><span>총 {filtered.length}개</span></div>
 {busy?<div className="file-empty">파일을 등록하고 있습니다…</div>:filtered.length===0?<label className="file-empty file-drop"><input type="file" accept={tab==="rtp"?"application/pdf":"audio/wav,video/mp4"} onChange={e=>void upload(e.target.files?.[0])}/><span>{tab==="rtp"?"PDF":"WAV / MP4"}</span><h3>등록된 파일이 없습니다.</h3><p>여기를 클릭해 첫 파일을 등록해 주세요.</p></label>:<div className="file-list">{filtered.map(file=><div className="file-row" key={file.id}><div className={`file-kind ${file.category}`}><b>{file.category==="rtp"?"PDF":"REC"}</b></div><div className="file-meta"><b>{file.name}</b><span>{formatBytes(file.size)} · {new Date(file.createdAt).toLocaleDateString("ko-KR")}</span></div><span className="file-status">등록 완료</span><a className="icon-action" href={`/api/files?id=${encodeURIComponent(file.id)}`} title="다운로드">↓</a><button className="icon-action danger" onClick={()=>void remove(file.id)} title="삭제">×</button></div>)}</div>}</section></>
}
function formatBytes(size:number){return size<1024*1024?`${Math.max(1,Math.round(size/1024))} KB`:`${(size/1024/1024).toFixed(1)} MB`}
